#%RAML 1.0
title: StagingUsers
version: v19.4.0
baseUri: http://github.com/org/folio/mod-users

documentation:
  - title: mod-users stagingUser API
    content: This documents the API calls that can be made to query and manage staging users of the system

types:
  stagingUser: !include staging_userdata.json
  stagingUserdataCollection: !include staging_userdataCollection.json
  outboxEventLog: !include outboxEventLog.json
  userEvent: !include userEvent.json
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml
  post-empty-body: !include raml-util/rtypes/post-empty-body.raml

/staging-users:
  type:
    collection:
      exampleCollection: !include examples/user_collection.sample
      exampleItem: !include examples/user.sample
      schemaCollection: stagingUserdataCollection
      schemaItem: stagingUser
  get:
    is: [
      searchable: {description: "", example: "email=abc@testEmail.com sortBy contactInfo.email"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Return a list of staging-users
  post:
    is: [ validate ]
    description: Create a user
