#%RAML 1.0
title: User tenants
baseUri: http://github.com/org/folio/mod-users

documentation:
  - title: mod-users User tenants API
    content: Records that show the primary tenant for a user when doing single-sign-on

types:
  userTenant: !include userTenant.json
  userTenantCollection: !include userTenantCollection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/user-tenants:
  type:
    collection:
      exampleCollection: !include examples/userTenantCollection.sample
      exampleItem: !include examples/userTenant.sample
      schemaCollection: userTenantCollection
      schemaItem: userTenant
  get:
    is: [
      pageable
    ]
    description: Return a list of user tenants
    queryParameters:
      userId:
        description: Filter by user id
        type: string
        example: 11484f66-5121-43ea-81e7-6d9e3711495f
        required: false
      username:
        description: Filter by user name
        type: string
        example: folio_user
        required: false
      tenantId:
        description: Filter by tenant id
        type: string
        example: sfs000
        required: false
      email:
        description: Filter by email
        type: string
        example: test@mail.com
        required: false
      phoneNumber:
        description: Filter by mobile number
        type: string
        example: "12345676"
        required: false
      mobilePhoneNumber:
        description: Filter by mobile phone number
        type: string
        example: "123456789"
        required: false
      queryOp:
        description: Query operation for searching
        type: string
        default: "and"
    responses:
      200:
        body:
          application/json:
            type: userTenantCollection
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
  post:
    is: [ validate ]
    description: Create a user-tenant
    responses:
      201:
        description: "Returns only 201 status code without body"
      400:
        description: "Bad request, e.g. malformed request body. Details of the error provided in the response."
      401:
        description: "Not authorized to perform requested action"
      422:
        description: "Validation error, e.g. missing required field. Details of the error provided in the response."
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
